The Python library for working with arrays and matrices is numpy, and the library for working with dataframes is pandas.

matplotlib is the standard plotting library, and seaborn

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import Seaborn

ImportError: No module named 'Seaborn'

In [5]:
x = np.array([1,3,2,5])
print(x)

[1 3 2 5]


In [10]:
x = np.array([1,6,2])
print(x)
y = np.array([1,4,3])

[1 6 2]


In [11]:
#multiple ways to find the length of a  numpy array
print(x.size)
print(len(x))

3
3


In [20]:
x+y

array([ 2, 10,  5])

iPython has some useful commands for inspecting the namespace

In [26]:
who

np	 pd	 plt	 x	 y	 


In [27]:
whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
pd         module     <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
plt        module     <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
x          ndarray    3: 3 elems, type `int64`, 24 bytes
y          ndarray    3: 3 elems, type `int64`, 24 bytes


In [28]:
del(x)

In [29]:
who

np	 pd	 plt	 y	 


In [38]:
#multiples ways to create a matrix

x = np.array([1,2,3,4])

In [62]:
# the .T transposes the array
print(x)
x = x.reshape(2,2).T
print(x)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [43]:
#technically x is *not* a matrix but a multi-dimensional array
type(x)

numpy.ndarray

In [49]:
# you could make a matrix a few different ways, this is the most straightforward
# to understand numpy's rehsape: http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.reshape.html
m1 = np.matrix([1,2,3,4]).reshape((2,2))
m1

matrix([[1, 3],
        [2, 4]])

In [50]:
m2 = np.matrix([1,2,3,4]).reshape((2,2), order='F')
np.sqrt(m2)

matrix([[ 1.        ,  1.73205081],
        [ 1.41421356,  2.        ]])

In [64]:
print("Notice that raising to the power 2 works elementwise on an array")
print(x**2)
print("But uses matrix multiplication on a matrix")
print(m2**2)
print("np.square(matrix) works elementwise, however")
print(np.square(m2))

Notice that raising to the power 2 works elementwise on an array
[[ 1  4]
 [ 9 16]]
But uses matrix multiplication on a matrix
[[ 7 15]
 [10 22]]
np.square(matrix) works elementwise, however
[[ 1  9]
 [ 4 16]]


In [68]:
# creating an array of normal random variables.
x = np.random.randn(50)

In [69]:
y = x + 0.1*np.random.randn(50) + 50

In [72]:
# note that this returns a correlation matrix
np.corrcoef(x,y)

array([[ 1.       ,  0.9934423],
       [ 0.9934423,  1.       ]])

In [73]:
# if you want pure pearson correlation coefficient and the 2-tailled p-value
from scipy.stats.stats import pearsonr
pearsonr(x,y)

(0.99344230319792315, 7.1502315873568479e-47)